FROM ubuntu:23.10

USER root

RUN apt-get update && apt-get install -y openjdk-17-jdk

RUN apt-get install wget -y 

RUN wget https://dlcdn.apache.org/spark/spark-3.4.3/spark-3.4.3-bin-hadoop3.tgz

RUN tar -xvzf spark-3.4.3-bin-hadoop3.tgz

COPY consumer.py ./

RUN apt-get update && apt-get install -y python3-pip 

RUN pip install pyspark==3.4.3  --break-system-packages

RUN pip install findspark  --break-system-packages

RUN pip install elasticsearch==8.2.0  --break-system-packages

RUN ln -s /opt/spark-3.4.3-bin-hadoop3 /opt/spark

ENV PATH="${PATH}:/usr/bin/python3"
ENV PATH="${PATH}:/opt/spark/spark-3.4.3-bin-hadoop3"

ENTRYPOINT ["spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.1", "consumer.py"]
